language: python
python: '2.7'
sudo: required
services:
- docker
branches:
  only:
  - master
before_install:
- docker version
- python --version
- javac -version
- java -version
install:
- pushd ..
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make bin
- make sdkbase
- export PATH=$(pwd)/bin:$PATH
- source src/sh/sdk-completion.sh
- popd
script:
- kb-sdk validate
